config:
  appDescription: "Mobile app Quiz Platform is an open-source knowledge testing platform. The user can play by completing tasks, track their progress, study theory in courses, review the theory from courses in practice mode, and so on. The tasks themselves resemble quizzes."
  sourceLanguage: "ru-RU"
  targetLanguages: [
    "zh-CN",
    "zh-Hant-TW",
    "hi-IN",
    "en-US",
    "en-GB",
    "es-ES",
    "es-MX",
    "es-419",
    "ar",
    "pt-PT",
    "pt-BR",
    "fr-FR",
    "fr-CA",
    "ru-RU",
    "bn-BD",
    "bn-IN",
    "ur-PK",
    "ur-IN",
    "am-ET",
    "ja-JP",
    "fil-PH",
    "vi-VN",
    "tr-TR",
    "fa-IR",
    "de-DE",
    "de-CH",
    "th-TH",
    "sw-TZ",
    "zu-ZA",
    "my-MM",
    "ko-KR",
    "pl-PL",
    "ms-MY",
    "ne-NP",
    "ne-IN",
    "mg-MG",
    "ha-NG",
    "km-KH",
    "so-SO",
    "ht-HT",
    "cs-CZ",
    "el-GR",
    "ro-RO",
    "hu-HU",
    "he-IL",
    "be-BY",
    "az-Latn-AZ",
    "da-DK",
    "fi-FI",
    "sv-SE",
    "nb-NO",
    "sk-SK",
    "ga-IE",
    "nl-NL",
    "kk-KZ",
    "uz-Latn-UZ",
    "tg-TJ",
    "ky-KG",
    "lo-LA",
    "bm-ML",
    "si-LK",
    "ta-IN",
    "uk-UA",
    "ps-AF",
    "ku-TR",
    "ckb-IQ",
    "bo-CN",
    "bo-IN",
    "mn-MN",
    "hy-AM",
    "sq-AL",
    "lt-LT",
    "lv-LV",
    "et-EE",
    "sl-SI",
    "hr-HR",
    "sr-Cyrl-RS",
    "sr-Latn-RS",
    "cnr-ME",
    "mk-MK",
    "bs-BA",
    "bg-BG",
    "ka-GE",
    "ti-ER",
    "ti-ET",
    "mt-MT",
    "dv-MV",
    "is-IS",
    "lb-LU",
    "ca-ES",
    "rn-BI",
    "rw-RW",
    "tn-BW",
    "tn-ZA",
    "st-LS",
    "st-ZA",
    "mr-IN",
    "te-IN",
    "pa-IN",
    "pa-PK",
    "jv-ID",
    "it-IT",
    "gu-IN",
    "yo-NG",
    "id-ID"
    # "sm-WS",
  ]
  aiProvider: "openai"
  aiKey: REPLACE_ME
  aiModel: "gpt-5.2"
  excludeTranslated: true

excludes:
  - "main_app_site_host"
  - "main_app_site_patch_prefix"
  - "main_app_telegram_chat_name"
  - "app_privacy_policy_link"
